### ISSUE TITLE
nether fortress spawning

### ISSUE THREAD

**Issue by grillotine** [axialeaa/DoormatCarpetExtension#12] opened 2024-09-30 22:57 UTC
i am testing out this mod for silly string in 1.21.1 and testing some other stuff in the same version and noticed this mod is somehow by default blocking any spawns from happening in a nether fortress, including blaze spawners. i did check a bastion remnant and it was spawning mobs, so im not sure if its exclusive to nether fortresses or if it goes beyond that. i tested this loading a brand new world without any carpet rules applied and it behaves the same. after removing the mod spawns occur again.

**Comment by axialeaa** [comment] 2024-10-01 00:25
this is *for sure* to do with `peacefulMonsterSpawning`. i'm honestly surprised something like this hasn't been reported already, since i've always been uncomfortable with how unstable the implementation has felt. i'll see what i can do

**Comment by axialeaa** [comment] 2024-10-05 22:58
without having reproduced the issue first, i made some changes (just for the sake of making the code better at a base level) and i now cannot observe the issue you're describing. whether this means i've fixed the issue or simply reduced the number of edge cases i'm not sure (nor able to check), but i'm feeling confident enough to close this report as fixed.

**Closed as completed by axialeaa** 2024-10-05 22:58 UTC
Labels: bug, priority level: moderate, status: implemented/fixed next update
